services:
#    core_business.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

 expense_manager:
     class:  FinanceBusinessBundle\Managers\ExpenseManager
     calls:
       - [ setContainer,[ "@service_container" ] ]
       - [ initialize ]