services:

    product_buttons:
        class: SanitarijeAdminBusinessBundle\Buttons\ProductButtons
        calls:
            - [ setContainer,[ "@service_container" ] ]
            - [ initialize ]

