css:
  - 'AppBundle/css/bootstrap/grid-layout/bootstrap.min.css'
  - 'AppBundle/css/fontawesome-free-5.15.1/css/all.min.css'
  - 'AppBundle/css/glyphicons/css/glyphicons.min.css'
  - 'AppBundle/js/plugins/datatables/dataTables.css'
  - 'AppBundle/js/plugins/datatables/fixedColumns.min.css'
  - 'AppBundle/js/plugins/dropzone/css/dropzone.css'
  - 'AppBundle/js/plugins/select2/dist/css/select2.min.css'
  - 'AppBundle/js/plugins/form-daterangepicker/daterangepicker.css'
  - 'AppBundle/js/plugins/bootstrap/bootstrap-switch/bootstrap-switch.min.css'
  - 'AppBundle/js/plugins/gridstack/dist/gridstack.min.css'
  - 'AppBundle/js/plugins/growler/jquery.growl.css'
  - 'AppBundle/js/plugins/jquery_menu_editor/bs-iconpicker/css/bootstrap-iconpicker.min.css'
  - 'AppBundle/js/plugins/fullcalendar/packages/core/main.min.css'
  - 'AppBundle/js/plugins/fullcalendar/packages/daygrid/main.min.css'
  - 'AppBundle/js/plugins/fullcalendar/packages/bootstrap/main.min.css'
  - 'AppBundle/js/plugins/fullcalendar/packages/list/main.min.css'
  - 'AppBundle/js/plugins/fullcalendar/packages/list/main.min.css'
  - 'AppBundle/js/plugins/growler/jquery.growl.css'
  - 'AppBundle/js/plugins/jquery_confirm/css/jquery-confirm.css'
  - 'AppBundle/js/plugins/multiselect/css/multi-select.css'
  - 'AppBundle/js/plugins/jquery/jqueryui.min.css'
  - 'AppBundle/js/plugins/c3js/c3.min.css'
  - 'AppBundle/js/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css'
  - 'AppBundle/js/plugins/magnific-popup/magnific-popup.css'
  - 'AppBundle/js/plugins/fancybox/jquery.fancybox.min.css'

  - 'AppBundle/css/blocks/*'
  - 'CrmBusinessBundle/css/blocks/*'
  - 'ScommerceBusinessBundle/css/blocks/*'
  - 'ToursBusinessBundle/css/*'


  #Default CRM style
  - 'style.css'

js:
  - 'AppBundle/js/plugins/jquery/jquery-1.10.2.min.js'
  - 'AppBundle/js/plugins/jquery/jqueryui-1.10.3.min.js'
  - 'AppBundle/js/plugins/jquery/form-autosize/jquery.autosize-min.js'
  - 'AppBundle/js/plugins/bootstrap/bootstrap.min.js'
  - 'AppBundle/js/plugins/bootstrap/bootstrap-switch/bootstrap-switch.min.js'
  - 'AppBundle/js/plugins/datatables/jquery.dataTables.min.js'
  - 'AppBundle/js/plugins/datatables/TableTools.js'
  - 'AppBundle/js/plugins/datatables/dataTables.bootstrap.js'
  - 'AppBundle/js/plugins/datatables/dataTables.buttons.min.js'
  - 'AppBundle/js/plugins/datatables/jszip.min.js'
  - 'AppBundle/js/plugins/datatables/pdfmake.min.js'
  - 'AppBundle/js/plugins/datatables/vfs_fonts.js'
  - 'AppBundle/js/plugins/datatables/buttons.html5.min.js'
  - 'AppBundle/js/plugins/yadcf/jquery.dataTables.yadcf.js'
  - 'AppBundle/js/plugins/bootstable/bootstable.js'
  - 'AppBundle/js/plugins/dropzone/dropzone.js'
  - 'AppBundle/js/plugins/select2/dist/js/select2.full.min.js'
  - 'AppBundle/js/plugins/gridstack/dist/gridstack.min.js'
  - 'AppBundle/js/plugins/gridstack/dist/gridstack.jQueryUI.min.js'
  - 'AppBundle/js/plugins/growler/jquery.growl.js'
  - 'AppBundle/js/plugins/ckeditor/ckeditor.js'
  - 'AppBundle/js/plugins/c3js/d3.js'
  - 'AppBundle/js/plugins/c3js/c3.min.js'
  - "AppBundle/js/plugins/jquery_confirm/js/jquery-confirm.js"
  - "AppBundle/js/plugins/jquery-number/jquery.number.min.js"

  - 'AppBundle/js/plugins/bootstrap/bootstrap-treeview/bootstrap-treeview.min.js'
  - "AppBundle/js/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"

  - 'AppBundle/js/plugins/fullcalendar/packages/core/main.min.js'
  - 'AppBundle/js/plugins/fullcalendar/packages/daygrid/main.min.js'
  - 'AppBundle/js/plugins/fullcalendar/packages/interaction/main.min.js'
  - 'AppBundle/js/plugins/fullcalendar/packages/bootstrap/main.min.js'
  - 'AppBundle/js/plugins/fullcalendar/packages/list/main.min.js'

  - 'AppBundle/js/plugins/jquery_menu_editor/jquery-menu-editor.js'
  - 'AppBundle/js/plugins/jquery_menu_editor/bs-iconpicker/js/iconset/iconset-fontawesome-4.2.0.min.js'
  - 'AppBundle/js/plugins/jquery_menu_editor/bs-iconpicker/js/bootstrap-iconpicker.min.js'

  - 'AppBundle/js/plugins/bootstrap_validator/dist/js/formValidation.min.js'
  - 'AppBundle/js/plugins/bootstrap_validator/dist/js/framework/bootstrap.min.js'

  - 'AppBundle/js/plugins/timeline/dist/js/timeline.min.js'
  - 'AppBundle/js/plugins/timepicker/js/bootstrap-timepicker.js'

  - 'AppBundle/js/plugins/form-daterangepicker/moment.min.js'
  - 'AppBundle/js/plugins/form-daterangepicker/daterangepicker.js'

  - 'AppBundle/js/plugins/form-daterangepicker/daterangepicker.js'
  - 'AppBundle/js/plugins/querybuilder/js/jquery-extendext.js'
  - 'AppBundle/js/plugins/querybuilder/js/query-builder.standalone.js'
  - 'AppBundle/js/plugins/magnific-popup/jquery.magnific-popup.min.js'
  - 'AppBundle/js/plugins/fancybox/jquery.fancybox.min.js'
  - 'AppBundle/js/plugins/maplace/maplace.min.js'

  - 'AppBundle/js/blocks/*'
  - 'AppBundle/js/fields/*'

  - 'CrmBusinessBundle/js/blocks/*'
  - 'CrmBusinessBundle/js/pages/*'

  - 'ScommerceBusinessBundle/js/blocks/*'
  - 'ScommerceBusinessBundle/js/front_blocks/*'
  - 'ScommerceBusinessBundle/js/pages/*'
  - 'HrBusinessBundle/js/*'
  - 'NotificationsAndAlertsBusinessBundle/js/*'
  - 'TaskBusinessBundle/js/blocks/*'
  - 'GLSBusinessBundle/js/pages/*'
  - 'DPDBusinessBundle/js/pages/*'
  - 'ToursBusinessBundle/js/*'

  - 'AppBundle/js/functions.js'
  - 'AppBundle/js/backend.js'
  - 'AppBundle/js/shipshape_admin.js'
  - 'AppBundle/js/shipshape_analytics.js'
  - 'AppBundle/js/shipshape_init_datatable.js'
  - 'AppBundle/js/shipshape_init_default.js'
  - 'AppBundle/js/shipshape_init_validation.js'