services:
    #    core_business.example:
    #        class: AppBundle\Example
    #        arguments: ["@service_id", "plain_value", %parameter%]


    factory_context:
        class: AppBundle\Factory\FactoryContext
        calls:
            - [ setContainer,[ "@service_container" ] ]

    factory_manager:
        class: AppBundle\Factory\FactoryManager
        calls:
            - [ setContainer,[ "@service_container" ] ]
